# Generated by Django 4.0.3 on 2023-02-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRitmoUrbano', '0009_contacto_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.CharField(max_length=200),
        ),
    ]
